//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XBlog.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class LocalGovernment
    {
    
        public int LocalGovernmentId { get; set; }
        public string LocalGovernmentName { get; set; }
        public string StateId { get; set; }
    }
}
